### ISSUE TITLE
Provide dataset management form

### ISSUE THREAD

**Issue by bryjbrown** [ldbase/ldbase_issues#10]
Users need a way of managing datasets uploaded to the site. A dataset content type can have multiple dataset files associated with it as different versions of the same dataset. This interface should allow users to:
- Delete a dataset version
- Replace a dataset file in a version
- Create a new dataset version
- Edit dataset version info

**Comment by barsenault-fsu** [comment]
The dataset displays the latest version of the dataset file.  When editing a dataset, uploading a new file will automatically create a new version.  If the user makes changes to other fields but not the file itself, then that will automatically edit the latest version.

There is a link to View All Dataset Versions.  From that view, users can edit any version.  They cannot change the file when editing because that would create a new version.  From the view, they can delete any version.

**Comment by barsenault-fsu** [comment]
From the Dataset, all users can see the latest dataset version and can get to the All Dataset View.

Project group administrators and editors can also:
- Create a new dataset versoin by uploading a new dataset file  
- Edit and delete dataset versions from the All Datasets View

We reviewed this in an update meeting, so I will close the issue.
