### ISSUE TITLE
Project Members - text change

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#102]
For embargo language on the Edit screens, where it currently says, "Access restriction exempt users
Enter LDbase users that are exempt from the access restriction."
Please change to:
Access Restriction Exempt Users
When you restrict public access to your data, the Project Administrators and Project Editors are the only people who can view those files. You can, however, allow certain individuals, such as a collaborator or a data requester whom you approve of, to override the restriction to view/download the data. Simply enter their LDbase name below. They will then gain access to this data, but they will not be able to to perform any actions that your Project Administrators and Project Editors can do. 

Please include a hyperlink on the first reference of the words "Project Administrators and Project Editors" that goes to the Edit Members page (and opens it in a separate window, so they can add people, then close it and come back to the window they were entering data on).   

THEN, on the Manage Members Page, please add this text, below the header in a smaller font to explain it:
This is where you can add/remove LDbase users who have the ability to edit your project's pages and data. There are two roles available. 

A Project Administrator can: 
Add/Edit all project metadata
Upload data to the project (datasets, codebooks, code, and documents)
Approve exempt access to certain users for any data you have embargoed (or do I need to say restricted from public view? are we not using the term embargoed?....)
Access/Edit embargoed data
Add/Remove Project Editors
Delete the project completely from LDbase
A Project Editor can:
Add/Edit all project metadata 
Upload data to the project (datasets, codebooks, code, and documents)
Approve exempt access to certain users for any data you have embargoed
Access/Edit embargoed data

(NOTE: Brian, we need help making sure the above list is correct? Also, can it be laid out visually, so its easy to see at a glance what the difference between the two roles are. For example, Project Admin with bulleted list on left half of screen, and Project Editor with bulleted list on right side of screen... and then you can see that the bottom 2 functions of the Project Admin do not exist for the Project Editors).

**Comment by barsenault-fsu** [comment]
I added code that updates the Access Restriction Exempt Users description.  If the user is a Project Administrator, then they get a link on the words "Project Administrators and Project Editors" that opens the Manage Members page for that project in another window.  (If the user is a Project Editor, then they don't have access to the Manage Members page and only get the text "Project Administrators and Project Editors" instead)

On the Manage Members page, I added the text but it will still need to be styled so that the lists appear in two columns on a wide-enough display.  It's a lot of text, so might some of it be better below the members table or otherwise displayed?

The only change I made in the lists of role permissions is that a Project Administrator can "Add/Remove Project Editors _and other Project Administrators_".

**Comment by trreynolds** [comment]
Could you also update the text on the below?
Restrict public access to files?
(Old text: Checking this box will make the submitted files unavailable to the public, but they will still be able to see your metadata.)
New text = Checking this box will make the submitted files unavailable to anyone who is not a Project Administrator or Project Editor of your project, but the dataset metadata will still be public.
Include the link again on those "Project Administrator or Project Editor" words like you did with the other line?

**Comment by barsenault-fsu** [comment]
Changes made.  Will update to Needs Review when moved to Test.
