### ISSUE TITLE
Add a "Browse all Items" button - front page?

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#106]
Links to a blank search, allows users to browse

**Comment by barsenault-fsu** [comment]
Front page links to browse, search, resources, and add data added.  Browse page also added.

**Comment by barsenault-fsu** [comment]
Changes to the Browse Page:
1. Content count bar graph
2. Contributions network graph

After updates the following enhancements will be on Test and Production:
1. the data visualization nodes and bars on the bar graph will be links to that item or group of items
2. The bar graph will have a hover that shows the count and type of item
3. the Browse by Vocabulary pages will list the taxonomy terms and the number of times that the term is used instead of just the term

**Comment by barsenault-fsu** [comment]
@trreynolds  Test has been updated and the changes to the Browse page are ready for review.

**Comment by barsenault-fsu** [comment]
empty search = browse all items
