### ISSUE TITLE
Changing all multiline inputs to pillbox style inputs

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#107]
Users are confused that there's no confirmation of their input, repeatedly click on the + button to "confirm" their input. Still attempt to use commas on one line. Pill box would solve all of these issues.

**Comment by barsenault-fsu** [comment]
It isn't possible to change all multiline inputs to the pillbox style inputs.  I'll document why below, but I could remove the + and - button from them if that's confusing.  An example would look like this:

![image](https://user-images.githubusercontent.com/54671134/107704305-05e3c800-6c8b-11eb-8f97-57098286ab06.png)

To add another, the user would have to use the "Add another Website" button.  The only way to remove a row would be to leave it blank.

**Why all multiline inputs cannot change to pillboxes:**

The pillboxes, or jQuery Select2 select boxes, are multiselect form elements.  Without all the jQuery around them they'd just look like this
![image](https://user-images.githubusercontent.com/54671134/107705413-ac7c9880-6c8c-11eb-91ba-a43113df47b5.png)

Between a setting in the Select2 element, and code that I wrote, it's possible to add items to the lists behind the select box.

I cannot change all the multiline inputs to be pillboxes, because not all the multiline inputs are select lists.  The "Your Website" example above is one of a few multiline text boxes.  There is no list behind it.  So the issue of multiline inputs as described would remain even if I changed other fields to pillboxes, but as it turns out, I can't do that either.

I also cannot change the contributor or organization multiline inputs into pillboxes, because the Select2 boxes won't allow you to add an item that already exists.  It will select the one that already exists instead.  So you could not have two people named "John Smith" for example.  When you try to enter a second one, it would  just select the already existing one.

There was an issue where pillboxes were adding new taxonomy terms multiple times, but I've fixed that.  What happened was that new terms were getting added to the taxonomy even if there were validation errors in the form.  The form would reload with the errors, but the select lists do not get refreshed in the form.  Since the form didn't see the new item in the list, even though it was already in the taxonomy, users could add the new term again.  It may be why the Entity Select isn't actually designed to add new taxonomy terms as we are.  I've changed the validation to check if there are errors, and if there are then to not add the new term.

**Comment by barsenault-fsu** [comment]
Since we can't change all the multiline inputs into pillboxes for the reasons outlined above, I'm closing this issue
