### ISSUE TITLE
Add email links

### ISSUE THREAD

**Issue by WilhelminavanDijk** [ldbase/ldbase_issues#114]
When adding a contributor or editor to a page, the email should include a link to that page, so that the newly added person can easily navigate to it.

**Comment by barsenault-fsu** [comment]
The email will now include a link to the page.  

I will update this as Needs Review when it is moved to Test.  It's possible that when the change is moved, that already existing messages will not display correctly, because the message template will have changed and older messages do not include the information needed to create the link.  New messages should work fine.

**Comment by barsenault-fsu** [comment]
A link to the content have been added to the messages when users are added as contributor and when users are added to a project group.  This is on production.  Closing issue
