### ISSUE TITLE
Embeds need to be changed to html

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#123]
Example here: https://ldbase.org/resources/best-practices/combining-data

Remove embeds, add content that was in embed to page as regular ol' html

**Comment by barsenault-fsu** [comment]
Converted pages on Test:

- https://test.ldbase.org/resources/best-practices/working-with-your-irb
- https://test.ldbase.org/resources/best-practices/general-data-management-guidelines
- https://test.ldbase.org/resources/best-practices/data-de-identification
- https://test.ldbase.org/resources/best-practices/combining-data
- https://test.ldbase.org/resources/best-practices/open-science
- https://test.ldbase.org/resources/templates/irb-application **
- https://test.ldbase.org/resources/templates/informed-consent-language **
- https://test.ldbase.org/resources/templates/data-management-plan

** These 2 papers use red text to distinguish text examples for open science.  I recommend using bold text rather than red text to distinguish the text based on Web accessibility success criteria [1.4.1 Use of Color: Color is not used as the only visual means of conveying information ….](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-without-color.html)  The font weight will be visible to users who may be colorblind.

**Comment by barsenault-fsu** [comment]
All changed to html and on Production.  We discussed changing the red text to bold at the 4/27 meeting and the team was okay with that.
Future edits can be done to the text on Production.
Closing
