### ISSUE TITLE
Add (unpublished) to the Object Title if it is Unpublished

### ISSUE THREAD

**Issue by Favenzio** [ldbase/ldbase_issues#126]
We need some way to signal to users that an object is unpublished. I thought a smart idea would be to add it to the title. This would be useful because then it would show up on the project tree. Once the project is published we would have to remove it.

**Comment by barsenault-fsu** [comment]
I pushed a handler update that will add " (unpublished)" to the title of objects if it isn't already there when they are unpublished.  When an item is published then it will remove " (unpublished)" from the end of the title.  

It's only checking for that specific string at the end of the title, so it's possible someone could add text to the title that could keep the code form automatically removing the " (unpublished)" but they can edit the title and fix it if needed.

Since the text is only getting added to unpublished items, only the people that can edit the object will see the extra text.

**Comment by barsenault-fsu** [comment]
Reviewed at 4/27 meeting and now on Production.  Closing issue.
