### ISSUE TITLE
New document for User Guide menu: Information To Gather Before Uploading Your Data

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#146]
Please place the text in the email I sent you (LDbaseRequestedFields.doc) under Menu: Resources-->User Guide--> put it here. The menu subheading can be: INFORMATION TO GATHER BEFORE UPLOADING YOUR DATA
Side note: We will eventually have two items in there (one will be a video walking people through LDbase), and this is the other. 

Jeffrey referenced page numbers at the very beginning of the document, so you might need to alter that (to links to jump ahead to that part of the text on the page?)

**Comment by barsenault-fsu** [comment]
Document for this issue

[LDBase Requested Fields.docx](https://github.com/ldbase/ldbase_issues/files/6825896/LDBase.Requested.Fields.docx)

**Comment by barsenault-fsu** [comment]
From a usability point of view, I'm going to break this document into a landing page with links to individual pages for the content types.  It's too long to make it a single page.  Since the text in #147 links to this new document(s), it will necessarily take more time to complete the new button issue..

**Comment by barsenault-fsu** [comment]
Content is on Production.  Closing issue.
