### ISSUE TITLE
Embargo banner sometimes displaying for search results

### ISSUE THREAD

**Issue by rkmase** [ldbase/ldbase_issues#161]
Reproduce using private browser:
1. Home page, top box search "sara"
2. Results have embargo banner 

![image](https://user-images.githubusercontent.com/67657370/191329124-906aafcd-6362-4a3e-a450-bec73d045b24.png)

**Comment by barsenault-fsu** [comment]
On Test, I set the embargoes module to not display the message on the search pages.

That's working correctly, I believe, but I just noticed the message can show up on other pages in certain cases.  I probably need to find a way **to** show it on the node page rather than **not** show it on search pages.  Still a WIP but the search pages should look right for testing.

**Comment by barsenault-fsu** [comment]
Fixed this so the embargo notice will only appear on the node display.
