### ISSUE TITLE
"Preview" button not working

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#162]
on "Create Article" (aka, creating a posting for the homepage newsfeed banner).

**Comment by barsenault-fsu** [comment]
duplicate of #156 

Preview doesn't work with new articles because the preview relies on a node id to display some information. Not a problem for other basic pages. Workaround is to save as unpublished, edit, then preview.
(from [10-26-2021 meeting notes](https://docs.google.com/document/d/1wlPEUeggdTjBk-8bgCJ0sYjid0Nvc4xoVwqieuP6ibI/edit#heading=h.69khqdkimrzr))
