### ISSUE TITLE
Leaving without saving

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#172]
When adding data, there is a message displayed if you click away without saving what you've done. At top of webpage, it says, "Leave site? Changes you made may not be saved." and there is a "Leave" and a "Cancel" button.

If you change the code's "Upload Code or Link to an external source" value, you do not get this message. Example: switch from 'I have a URL' to 'I will upload the Code'... and upload a file, then click away. You do not get that warning message.

Should I check this for more fields or do you think it's just this one that needs fixed?

**Comment by barsenault-fsu** [comment]
If you change the "Upload Code or Link to an external source" value, you don't get a message about leaving the site/page, because you aren't leaving the site or page.  You are toggling between 2 options on the same form.  It is the same with datasets and Documents.  I don't see that there is anything to fix.  This is expected behavior.
