### ISSUE TITLE
Search Results - Left Hand Results By Category

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#20]
SHart request: make "Participant Age" one of the limiters on the left hand side of a search result. I'd be open to dropping Time Method for AGE instead. And age should go under participant type in the list.

**Comment by bryjbrown** [comment]
I've set up individual facet blocks for minimum age and maximum age, both are range sliders that allow you to select a lower and upper bound for narrowing search results. This is the most usable way that I could think to do it, as this is actually a lot more complicated than it seems.

**Comment by Favenzio** [comment]
@bryjbrown during testing we found an issue where participant range does not appear to update correctly based on the data from the results. For example, there was a dataset with participant ages 45 - 55, but the filters only allowed filtering between 4 and 7.

**Comment by WilhelminavanDijk** [comment]
A different issue, but related to search by categories:

The filters on the search are not quite intuitive. Right now, each filter appears at the bottom of each category. It wasn't clear to me at first that that was what was happening. If you select multiple filters, for example, each filter stays under their own category. 
Would it be possible for the filter to show up as pill boxes above the search? That way it would be clear how the search was filtered and easier to drop filters a user doesn't want. Alternatively, instead of clicking on the "links" on the left, we see checkboxes as an option to select filters.

**Comment by bryjbrown** [comment]
@WilhelminavanDijk I have copied you last commend (https://github.com/ldbase/ldbase_issues/issues/20#issuecomment-697325605) to https://github.com/ldbase/ldbase_issues/issues/50 since it is a separate issue.

**Comment by Favenzio** [comment]
Solution has been accepted.
