### ISSUE TITLE
Typing in "other" project descriptors (pillbox selection items)

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#36]
Step: Create Project.  On the pillbox items, I can type text into that field , and it looks like it accepts my text, but it doesn't. And it says that everything was successfully saved. Is that ok?
Walk through:  go down to "Educational Curricula" and click on that box. Type in a word. Click save, and it saves it. But the words I typed were not saved (because our process is to select "other" and then type it. But still, in my mind, since I typed a curricula in there, I would think that it would be saved, right?)

**Comment by barsenault-fsu** [comment]
Since those fields are multi-select fields, and the typed-in text is not a selection, the extra text doesn't get saved.  I have tried to clear the text when the user leaves the box, but doing that breaks the dropdown selection list.  

Could we, as an alternative, add some text like "Please select items from the list" similar to the "Please enter ..." and "Please include ..." text for other fields on the Project form?  That might be friendlier than "Unselected text will not be saved."

**Comment by barsenault-fsu** [comment]
This issue is related to #21.  The pillbox selection items will now allow users to add new items.  New items will automatically be added to the selection list.  

Work that still needs to be done on this item: 

- add a "Needs Review" field to affected taxonomies
- trigger email to system administrators when new terms are added
- create administrative interface to review (accept, edit, repoint?, and delete) terms

If this new system is acceptable, then, regarding issue #21, the "Other" fields, the code that makes the fields visible, and the term "Other" could probably be removed, correct?

**Comment by trreynolds** [comment]
Your new method is awesome! As far as I'm concerned, you can close this.

**Comment by barsenault-fsu** [comment]
Now there is a notification message, and an interface that allows admins to edit, delete, and uncheck that user-added taxonomy terms need review.  At some point they may need an interface for merging terms.  That can be a new issue.  Closing this one.
