### ISSUE TITLE
Person: profile picture uploads, but isn't visible

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#37]

**Comment by Favenzio** [comment]
Picture shows now. Leaving the ticket open because we need to ensure that image upload resizes the file to a standard size.

**Comment by WilhelminavanDijk** [comment]
I added a pretty "big" pic of myself: on the "my dashboard" page it is huge, but on the 'person' page it is a reasonable size.
Take a look and see if that helps you :)

**Comment by barsenault-fsu** [comment]
The images now get resized when they are uploaded to fit in a 200px by 200px square, maintaining their aspect ratio.  If the image you upload is rectangular, then the resized image will still be a rectangle whose longest sides are no more than 200 pixels long.

The resize happens when the image is uploaded so any big picture uploaded before this feature was implemented will still appear too big.  To fix, just re-upload the image and save.

Closing this.
