### ISSUE TITLE
Creating a "New User" Account (Person)

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#40]
I don't see where I can add the fields that Sara mentioned in her document: other personal info, google scholar, orcid, social media, github, key search terms for investigators, etc.

**Comment by WilhelminavanDijk** [comment]
I see the fields Tara mentioned above.

One of them is not working: the add area of expertise. I can only do type in the box, but am not getting additional boxes. When typing in it and trying to submit, I get an error message and the page doesn't save. Without typing in that box, it does save.

**Comment by barsenault-fsu** [comment]
Regarding the area of expertise field, it looks like there was a Webform issue with entity autocomplete fields (https://www.drupal.org/project/webform/issues/3155914) but the fix is included in webform 8.x-5.20-beta1  The webform updates come pretty regularly so this should be rolled out soon.  Will keep an eye on it.

**Comment by trreynolds** [comment]
Google Scholar ID field is missing.

**Comment by barsenault-fsu** [comment]
Google Scholar ID added to Person profile form.  Will update with "Needs Review" label when pushed to Test.

**Comment by barsenault-fsu** [comment]
Google Scholar ID field is not on the Profile form and ready for review.

**Comment by Favenzio** [comment]
Solution has been accepted.
