### ISSUE TITLE
Project Level labels 

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#44]
When you are viewing a Project, the "Schooling" label should be "Educational Environment"
"Curricula" should be "Educational Curricula"
"Time Method" should be "Developmental Design"

**Comment by bryjbrown** [comment]
@trreynolds Do you mean ONLY for the display of the project, or should this be the case for the webform as well? Having it be one thing in the webform but a different thing in the display might confuse users.

**Comment by trreynolds** [comment]
What is a webform and what is a display? Thanks :)

**Comment by barsenault-fsu** [comment]
@trreynolds the webforms are the edit forms, like when you click "Edit this Project" and get all the fields.  The displays are the views of the saved data without the fields to edit them, like when you click on a Project link in the Project Navigation block.  So when you say "viewing a Project" it could mean only the display rather than both the form and the display.

**Comment by trreynolds** [comment]
I agree. They (Edit or View screen) should be the same. It looks to me like they are different, so I am trying to get the two to match up. The terms above are what should be used.

**Comment by barsenault-fsu** [comment]
Okay, thank you.  It looks like the webform has the correct labels and the labels need to change in the Project display to match, so I'm going to tag @Favenzio on this.

**Comment by Favenzio** [comment]
Solution has been accepted.
