### ISSUE TITLE
Download Whole Project

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#71]
Give the public a way to download EVERYTHING from the project page. (Datasets, codebooks, etc. all at once, one click.)

**Comment by barsenault-fsu** [comment]
On Test for review:

1. On the Project view, next to the citation button is a "Download all Project Files" button that appears when there are files in the project hierarchy that the user can access. 
2. Clicking the button creates a .zip file and sends it to the browser for download.
3. The folder structure in the zip file mirrors the project hierarchy (e.g. "project_name/dataset_name/file_name.xlsx" would be the dataset file)
4. At the top level of the zip file is a txt file (FILES_IN_THIS_ARCHIVE.txt) with a list of what is in the zip file
5. The zip file will not include files that the user cannot access, such as embargoed or unpublished files.

**Comment by WilhelminavanDijk** [comment]
Ok. The button appears, but Tara and I found the following. 
1. If you have two datasets in a project, neither will be downloaded if one of them is embargoed. (should download 1, not 0)
2. if you have two datasets in a project, both of them will be downloaded even if one is unpublished. (should download 1, not 2).
Then i tested with documents where I have 1 published, 1 published and embargoed, and 1 unpublished, and they all were downloaded, instead of just the one published.

I'm attaching the txt file of the last test fyi.
[FILES_IN_THIS_ARCHIVE.txt](https://github.com/ldbase/ldbase_issues/files/6366110/FILES_IN_THIS_ARCHIVE.txt)

**Comment by trreynolds** [comment]
Yes! It's perfect. Thanks!
