### ISSUE TITLE
Subscribe to get dataset version updates

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#72]
Since we are allowing versions of datasets, people should be able to "subscribe" to get an update (email) if/when it happens.

**Comment by barsenault-fsu** [comment]
On Test  now.  

1. When a logged in user views a Dataset with an uploaded file, a "Get Updates" button appears next to the "Get Citation" button
2. Clicking the Get Updates button goes to a confirmation form asking if the user wants to receive an email when a new version of the dataset file is uploaded
3. If the user confirms, then they return to the Dataset view and the button now reads "Stop Updates"
4. If a new file is uploaded, an email is sent to all users who have subscribed to that dataset with a link to the dataset.
5. The email also says that the user received the email because they requested to be notified and tells them if they want to stop notifications then they can click the "Stop Updates" button

**Comment by trreynolds** [comment]
Great! In the email message, it says to click on the link "above" (but my link is actually below). Is your link below too? If so, just change the wording to say "below". Also in the message you say, "use the link above to view the dataset and there click the "Stop Updates" button."  Maybe you meant to say, "....and THEN click..."?

**Comment by trreynolds** [comment]
I clicked to STOP UPDATES but I still received them.  (same question as other github... maybe it just takes a day to work?)

**Comment by barsenault-fsu** [comment]
@trreynolds 
1. Link text and above/below: I'll change this text "If you no longer wish to receive these notifications, use the link above to view the dataset and there click the "Stop Updates" button." to this "If you no longer wish to receive these notifications, view the dataset, click the "Stop Updates" button, and then click the "Confirm" button."  It looks like the email separates the link URL from the link text and puts the URL at the end of the message.  The message template itself has the link on the name of the dataset and was therefor above when I created it.
2.  Regarding still receiving updates: the tara_fcrr@outlook.com is still listed as subscribed to the birds embargoes dataset, so that account is going to receive messages.  When you click the button to stop updates and then confirm, then that account is removed from the list immediately.  I tested with my own account and I tested removing and adding back the tara_fcrr@outlook.com account. It worked to remove the subscription immediately and add it back.  I'm not seeing the issue with stopping updates.  If you continue to have the issue, we'll need to have a Zoom or Teams call so you can walk me through the problem.  I can't replicate it.

**Comment by trreynolds** [comment]
1. It's good with one grammar change. Please paste this text:  If you no longer wish to receive these notifications: view the dataset, click the "Stop Updates" button, and then click the "Confirm" button."
2. Perfect

You can close this after making the text change. Thanks!

**Comment by barsenault-fsu** [comment]
1. changed the message text.  Update is on Test.

**Comment by trreynolds** [comment]
One more edit (lol). I tried it, and it brought me to the dataset screen (perfect) but I couldn't find the "Stop Updates" button because I wasn't logged in. Just to prevent them from contacting us, can you add this one little bit to the existing language ?
If you no longer wish to receive these notifications: Log in to LDbase, view the dataset, click the "Stop Updates" button, and then click the "Confirm" button.

**Comment by barsenault-fsu** [comment]
1. Changed the message text, adding "Log in to LDbase"
2. The update notification now also gets sent when an embargo is removed from the dataset (request from 4/27 meeting)

**Comment by barsenault-fsu** [comment]
Changes are on Production.  Closing issue.
