### ISSUE TITLE
Published Flag

### ISSUE THREAD

**Issue by trreynolds** [ldbase/ldbase_issues#76]
When entering information to LDbase, a person COULD choose to save it as a draft = unpublished. This means the metadata is only visible to project admin/project editors but not the public, until they are ready to publish to the web. This is different from embargo (where metadata is still visible to public, but data isn't).
This would be at the content node level (Project, Dataset, Codebook...), because you could, say, publish a project but not publish a dataset. 
We are thinking maybe there could be two buttons at the bottom of each content node. Instead of just the current "Submit" button, maybe have two buttons, and they have to choose which to click? (One saves and publishes to internet; one saves as a non-public-viewable draft).
Text from Sara: By clicking Save (or "Save and Publish" whatever we choose to name it), you are making your metadata (which is the information you entered above, e.g. Project Name, Assessments Used, any uploaded documents) permanently available to the public. If you have chosen to embargo your dataset(s), the dataset(s) will not be publicly available but your metadata will be. (wording to be determined since embargo system is not yet in place) (and is "permanently"appropriate since they actually can delete at any point in time?)
Like a draft vs. final version. 
Send email to Project Admin and Project Editors if they haven't published it after 30 days to remind them. And maybe every 30 days? We want to push data to be public. This is a public repository grant.

**Comment by rkmase** [comment]
Note from UX testing: May want to consider changing "Submit" to "Save" or something more appropriate.

**Comment by barsenault-fsu** [comment]
Not yet on test, but noting here:   added checkboxes to the webforms that ask,  "Make this information publicly available?" and have a description text that reads, "If you uncheck this box, users will not be able to view or search for any metadata (i.e. information) about your ______ (project, code, document, etc.). You can uncheck the box to save the metadata as a draft and later check the box to share it publicly. If you have chosen to embargo your files, the files will not be publicly available, but your metadata will be."

Also changed the "Submit" buttons to "Save"

**Comment by trreynolds** [comment]
While testing this weekend, I did not publish a project, but I did publish it's associated dataset, which is odd, so I'm wondering if we need to control this a bit more. (If you want to see an example of my thoughts: I did not publish the Lion project. But I published the Lions dataset on ldbase.org. What happened was: it allows a viewer to see a dataset, but viewer cannot get treeview, or any project information, AND they get an unknown error when trying to download the dataset anyway)  So maybe:

1.) If they did NOT publish at the Project Level (aka UNPUBLISHED PROJECT), then all content nodes must default to UNPUBLISHED.
     1a.) When they move from unpublish to publish at Project Level, is there an easy way via your code to ask them if they want to also publish the rest of their nodes?
2.) IF they did publish at the Project level, they can then decide whether or not to check "publish" at each content node level, like we have it now (AKA publish dataset 1, but not dataset 2 and not document1).

If we do this, we would need to update the Help Text (under the "?") for the PROJECT level to say: By checking this box, you are making the above information available to the public for searching. As you progress through LDbase and enter the rest of your project (datasets, codebooks, presentations, etc), you will have the capacity to choose, for each piece of data, whether to publish that metadata and data or to temporarily save it as a draft while you complete/gather those specific research details."

Help text for the DATASET content node should say, "By checking this box, you are making the above metadata and data available to the public. If you have chosen to embargo your dataset, the dataset will not be publicly available but your metadata will be. If you cannot check this box, you need to first publish your project at the Project level." 

Help text under any other content node should say, "By checking this box, you are making the above metadata and data available to the public. If you cannot check this box, you need to first publish your project at the Project level."

Also.. don't close this github until email reminder (see initial github text) is setup. We don't want people keeping unpublished stuff on ldbase lol!

**Comment by barsenault-fsu** [comment]
@ldbase/issue-managers  I experimented with a couple things and thought about this some.  When it comes to disabling the "Publish on LDbase" checkbox, we really only need to check the parent of the item that we are adding or editing.  We don't need to check the whole tree.  If you don't publish the project you add, then the dataset cannot be published when you add it.  Even if you were 14 levels deep into a project, the status that only really matters when you load a form is the published status of the parent node.

With that in mind, and with the changes to the help text above:

1) I can set it so that when a form loads, it checks its parent, and if that parent node is not published, then the "Publish on LDbase" checkbox will be unchecked and disabled so they cannot check it.

2) If an item is changed to unpublished, then it AND its descendants will be unpublished.  This is similar to deleting an item.  We should probably add Help text about this too.

3) If an unpublished item is changed to published, then we can have a javascript pop-up remind them to publish also any child items that they want to be available to the public.

Sound like a plan?  --Brian

**Comment by Favenzio** [comment]
Sounds like a plan to me Arsenault. 👍

**Comment by barsenault-fsu** [comment]
Changes are on test for review.  One clarification regarding the help text changes: the text above mentions "if you cannot check this box, you first need to publish at the project level."  This is only true if the item you are trying to publish is attached directly to the project.  If you had a published project, an unpublished dataset attached to it, and you added a codebook to the dataset, then you wouldn't be able to publish the codebook, because the dataset is unpublished.  I changed the text to "publish the item above this in the project hierarchy," which is the heading on the project structure/navigation/tree menu.

Deployed changes:

1. Made text changes to "Publish on LDbase" help 
2. If you unpublish an item, it will unpublish all the items below it in the project hierarchy and give the user a message like, "Dataset successfully saved.  6 child nodes also unpublished."  (This has to happen to maintain the hierarchy structure.)
3. If you add or edit a node and its parent is unpublished, then the "Publish on LDbase" checkbox is disabled and unchecked.  Additionally a message appears below the checkbox that "You may save, but to publish this item you must first publish its parent [Type and Title of Parent Content]"  So it tells you what you would need to publish first.
4. If you do change an item from unpublished to published, then you get the "Success" message and if it has unpublished descendants: "Remember to publish the other items in your project hierarchy so the metadata will be shared."
5. A script will run weekly to check if there are any unpublished items that have not been edited for 30 or more days.  If there are, then the item's Project administrators will get an email with a link to the item asking them to consider checking the Publish on LDbase box to share their metadata with the public.

**Comment by barsenault-fsu** [comment]
As of 4/1 The "Publish on LDbase" box is unchecked by default.  Users will need to check the box to publish their metadata.

**Comment by trreynolds** [comment]
Looks great! I really like the "Remember to ....." message when you move Project from unpublished to published. I think these messages help our users. Thanks!

**Comment by barsenault-fsu** [comment]
Changes accepted.  Closing.
