### ISSUE TITLE
Project Members Screen: Add List of Embargo Exceptions

### ISSUE THREAD

**Issue by Favenzio** [ldbase/ldbase_issues#88]
In order to provide a Project Administrator a full picture of the access granted to the project, it would be a good idea to add a second table under the  List of Users. The new table could be titled, "Granted Embargo Exceptions". It would be a list of all the users that have been granted exceptions to embargoes. The columns could be: 'username', 'File to be Accessed' and 'embargo duration'. We could also provide a link to remove the access grant.

**Comment by barsenault-fsu** [comment]
This is now on Test and ready for review.

Project Administrators can click on a Project > Manage Members and now see a button that reads "View Granted Embargo Exemptions."  Clicking that button lists the Exempt Users and the files they can access in this project's hierarchy.  Each row has two operation links.  One is to view the item, which goes to the view of the embargoed item (e.g. dataset, code, or document).  The other link goes to a confirmation form to remove that user's access to the embargoed material without having to go and edit the material itself.

**Comment by trreynolds** [comment]
@barsenault-fsu  I made someone an embargo-exception (so they could see the embargoed dataset, and they could); then removed them, but they could still see the embargoed dataset. Does it take a while to change, maybe?

**Comment by trreynolds** [comment]
@barsenault-fsu  
1.) I granted access to a person. When that person views the dataset, it still says the dataset is under embargo, and it says "Access to this file is restricted" (in red) but you can click on it and download it. I assume it shouldn't say access is restricted in red?
2.) I had a second person ask for access. When I granted access to the embargoed item (from the automated email it sent me), it said "Status messageThe user already has access to the embargoed material."  (NOTE: it was the second person I was granting access to, in case that makes a difference?) so I couldn't give access to them.

**Comment by barsenault-fsu** [comment]
@trreynolds 
I'm sorry but I need to know which account you were using and which account you were adding on which dataset.  Please list out the steps you went through.  Otherwise I'm just guessing to try to recreate the issue.  

Also make sure when you switch users that you don't open another tab and do it there.  Log out and log back in from one tab, otherwise it's possible to get mixed up session variables.  I'm not sure if that's what you're doing, but I'm trying to reduce the number of possible issues.  Thank you.

**Comment by barsenault-fsu** [comment]
This is not on test yet, but I think I have guessed what is going on.  Once the fix is pushed to Test I'll update the label on this issue.

First, I want to assure everyone that if a file is embargoed, then it cannot be downloaded.  The problem here was that the dataset view (or document view or code view, etc.) is cached, which normally gets refreshed when the dataset (or document etc.) is saved/updated.  I forgot that when granting or revoking an exemption to the embargo, only the embargo and not the dataset (etc.) itself is saved/updated.  So access was granted or revoked, but the display wasn't refreshing.  Again, the access itself was correct, but the link text wasn't keeping up.

Here's what I did to test this, with User 1 and User 2 in a separate browsers:
1. In one browser, created a Project and Dataset upload as User 1
2. In a separate browser, viewed the dataset as a non-logged in user (anonymous user) and as User 2.  Everything accessible.  The file downloads.
3. As User 1, restricted access (placed an embargo) on the Dataset file by editing the dataset
4. As User 2: without refreshing the page in the other browser the file link still looks accessible (expected since User 2 had not reloaded the page), but clicking on the file link goes to the Access Denied screen.  The file does NOT download. (good)  User 2 refreshed the dataset page and now the link is red and says that access is restricted. (good)
5. User 2 requests access to the dataset, User 1 grants access
6. User 2, without refreshing the dataset page in the other browser clicks to download the file and it downloads (good because access was granted), but because User 2 hadn't refreshed the page, the link is still red and says that access is restricted (expected since User2 had not reloaded the page). When User 2 did refresh the page the link continued to look restricted because Drupal kept sending the cached version of the dataset page which had not been refreshed. (bad) 

I have added code that will refresh the dataset (document, code, etc.) cache when access requests are granted and when access is removed through the Granted Embargo Exemptions view.  So when User 2 reloads the page in Step 6, the link will appear correctly.

**Comment by trreynolds** [comment]
If I have an embargoed dataset, and two outside people request access to it, it sends me two emails (with requests to approve them).
I click the first email, and it approves that person and adds them to my DATASET EDIT screen as approved for access.
I click on the second email, and it says that person is already approved (but they are not, and they are never given access). 
I was thinking the email link was the same link (but for two people? So both people can't get access?) but they look different to me.

**Comment by barsenault-fsu** [comment]
There was a syntax error in the confirmation form that prevented more than one user from getting added.  Sorry for the confusion.
The fix has been pushed to Test.

**Comment by barsenault-fsu** [comment]
On Test now:
Discussed at the 4/27 meeting: If a user can access an embargoed item, whether as an exempt user, admin, or editor, then the embargo details in the left column and the orange information at the top of an embargoed item page will have one of these added lines of text:
- "You have been granted an access exemption to this resource."
- "You have access to this resource as a Project Administrator."
- "You have access to this resource as a Project Editor."

Also added a message notification when a user's request for access is approved.

**Comment by barsenault-fsu** [comment]
I added additional user context to the side block to prevent caching issues.

**Comment by barsenault-fsu** [comment]
These changes and fixes have been moved to Production.  If you notice something out of sorts you can reopen this issue.
